name: BuildDockerImage

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    paths:
      - 'requirements.txt'
      - 'Dockerfile'

jobs:

  buildImage:

    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build ContainerImage
        run: docker build -t ghcr.io/${{ github.repository_owner }}/numiz-monitor/numiz-monitor-launcher:latest

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to Github Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/numiz-monitor/numiz-monitor-launcher:latest